"""
selenium_tools/placement_scraper.py
Comprehensive IT Company Placement Data + Naukri IT Jobs
No live scraping needed — full company profiles with eligibility, roles, apply links.
"""

from datetime import datetime

# ─── Full IT Company Placement Database ──────────────────────────────────────

PLACEMENT_COMPANIES = [
    {
        "name": "Zoho Corporation",
        "logo": "🟦",
        "hq": "Chennai, Tamil Nadu",
        "available": True,
        "badge": "🔥 Hiring Now",
        "badge_type": "hot",
        "careers_url": "https://careers.zohocorp.com/jobs/Careers",
        "apply_url": "https://careers.zohocorp.com/jobs/Careers",
        "roles": [
            {"title": "Member Technical Staff", "type": "Full Time"},
            {"title": "Software Developer", "type": "Full Time"},
            {"title": "UI Developer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech in CSE / IT / ECE",
            "percentage": "60% and above throughout academics",
            "backlogs": "No active backlogs at time of joining",
            "gap": "No academic gap allowed",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["C", "C++", "Java", "Python", "Data Structures", "Problem Solving"],
        "package": "5 – 12 LPA",
        "location": "Chennai, Coimbatore, Tirunelveli",
        "process": "Aptitude Test → Coding Round → Technical Interview → HR",
        "category": "Product",
    },
    {
        "name": "Wipro Technologies",
        "logo": "🟩",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🆕 New Drive",
        "badge_type": "new",
        "careers_url": "https://careers.wipro.com/careers-home/jobs",
        "apply_url": "https://careers.wipro.com/careers-home/jobs",
        "roles": [
            {"title": "Project Engineer (Turbo)", "type": "Full Time"},
            {"title": "Project Engineer (Elite)", "type": "Full Time"},
            {"title": "IT Analyst", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA / M.Tech (any branch)",
            "percentage": "60% and above in 10th, 12th, Degree",
            "backlogs": "No active backlogs",
            "gap": "Max 1 year gap acceptable with valid reason",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Java", "Python", "SQL", "Communication Skills", "Aptitude"],
        "package": "3.5 – 6.5 LPA",
        "location": "Pan India (Bangalore, Hyderabad, Chennai, Pune, Mumbai)",
        "process": "NLTH Test → Technical Interview → HR Interview",
        "category": "Service",
    },
    {
        "name": "Infosys",
        "logo": "🔴",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🔥 Mass Hiring",
        "badge_type": "hot",
        "careers_url": "https://career.infosys.com/joblist",
        "apply_url": "https://career.infosys.com/joblist",
        "roles": [
            {"title": "Systems Engineer", "type": "Full Time"},
            {"title": "Digital Specialist Engineer", "type": "Full Time"},
            {"title": "Associate", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA / M.Sc (CS) / M.Tech",
            "percentage": "65% and above throughout (10th, 12th, Degree)",
            "backlogs": "No active backlogs",
            "gap": "Max 2 years gap acceptable",
            "batch": "2023 / 2024 / 2025 passout",
        },
        "skills": ["Programming Basics", "DBMS", "OS", "Networking", "Aptitude", "English"],
        "package": "3.6 – 8 LPA",
        "location": "Pan India",
        "process": "Online Test (HackerRank) → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "Cognizant (CTS)",
        "logo": "🔵",
        "hq": "Chennai, Tamil Nadu",
        "available": True,
        "badge": "🆕 GenC Drive",
        "badge_type": "new",
        "careers_url": "https://careers.cognizant.com/global/en",
        "apply_url": "https://careers.cognizant.com/global/en/search-results?keywords=fresher",
        "roles": [
            {"title": "Programmer Analyst Trainee (GenC)", "type": "Full Time"},
            {"title": "Programmer Analyst (GenC Elevate)", "type": "Full Time"},
            {"title": "GenC Next – Specialist", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / B.Sc / BCA / MCA / M.Tech",
            "percentage": "50% and above throughout academics",
            "backlogs": "No active backlogs at time of joining",
            "gap": "Max 2 years gap allowed",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["C", "Java", "Python", "SQL", "Reasoning", "Verbal Ability"],
        "package": "4 – 7 LPA",
        "location": "Chennai, Bangalore, Hyderabad, Pune, Kolkata",
        "process": "CPARS Test → Coding Test → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "HCL Technologies",
        "logo": "🟣",
        "hq": "Noida, Uttar Pradesh",
        "available": True,
        "badge": "✅ Open",
        "badge_type": "open",
        "careers_url": "https://www.hcltech.com/careers",
        "apply_url": "https://www.hcltech.com/careers/job-listings",
        "roles": [
            {"title": "Graduate Engineer Trainee", "type": "Full Time"},
            {"title": "Technology Analyst", "type": "Full Time"},
            {"title": "Software Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech in CSE / IT / ECE / EEE / Mechanical",
            "percentage": "60% and above (no rounding off)",
            "backlogs": "No active backlogs",
            "gap": "Max 1 year gap",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["C++", "Java", "Networking", "OS Concepts", "Problem Solving"],
        "package": "3.5 – 5 LPA",
        "location": "Chennai, Noida, Bangalore, Hyderabad, Lucknow",
        "process": "Aptitude Test → Group Discussion → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "Oracle India",
        "logo": "🟠",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🔥 Hiring Now",
        "badge_type": "hot",
        "careers_url": "https://careers.oracle.com/jobs",
        "apply_url": "https://careers.oracle.com/jobs/#en/sites/jobsearch/jobs?keyword=fresher+india",
        "roles": [
            {"title": "Associate Software Engineer", "type": "Full Time"},
            {"title": "Cloud Engineer", "type": "Full Time"},
            {"title": "Applications Developer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech in CSE / IT",
            "percentage": "70% and above throughout",
            "backlogs": "No backlogs — active or historical",
            "gap": "No gap allowed",
            "batch": "2025 passout preferred",
        },
        "skills": ["Data Structures", "Algorithms", "SQL", "Java", "Python", "System Design"],
        "package": "8 – 18 LPA",
        "location": "Bangalore, Hyderabad",
        "process": "Online Coding Test → 3 Technical Rounds → HR Round",
        "category": "Product",
    },
    {
        "name": "TCS (Tata Consultancy Services)",
        "logo": "🏢",
        "hq": "Mumbai, Maharashtra",
        "available": True,
        "badge": "🔥 NQT Drive",
        "badge_type": "hot",
        "careers_url": "https://www.tcs.com/careers",
        "apply_url": "https://nextstep.tcs.com/campus/",
        "roles": [
            {"title": "Assistant System Engineer Trainee", "type": "Full Time"},
            {"title": "System Engineer", "type": "Full Time"},
            {"title": "TCS Digital Role", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / M.Tech / MCA / M.Sc (any branch)",
            "percentage": "60% and above in 10th, 12th, and Degree",
            "backlogs": "No backlogs during entire academic career",
            "gap": "Max 2 years cumulative gap",
            "batch": "2023 / 2024 / 2025 passout",
        },
        "skills": ["Quantitative Aptitude", "Reasoning", "Programming", "English", "DSA"],
        "package": "3.36 – 7 LPA (NQT basis)",
        "location": "Pan India — 200+ locations",
        "process": "TCS NQT (National Qualifier Test) → Technical → Managerial → HR",
        "category": "Service",
    },
    {
        "name": "Accenture",
        "logo": "🔶",
        "hq": "Mumbai, Maharashtra",
        "available": True,
        "badge": "🆕 New Openings",
        "badge_type": "new",
        "careers_url": "https://www.accenture.com/in-en/careers",
        "apply_url": "https://www.accenture.com/in-en/careers/jobsearch?jk=fresher",
        "roles": [
            {"title": "Application Development Associate", "type": "Full Time"},
            {"title": "System & Application Services Associate", "type": "Full Time"},
            {"title": "Advanced App Engineering Analyst", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA / M.Sc / BCA (any branch)",
            "percentage": "60% and above throughout",
            "backlogs": "No active backlogs at joining",
            "gap": "Max 2 years gap",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Java", "Python", "Cloud Basics", "SQL", "Communication", "Teamwork"],
        "package": "4.5 – 8 LPA",
        "location": "Bangalore, Hyderabad, Chennai, Mumbai, Pune, Delhi",
        "process": "Communication Check → Cognitive + Technical Test → Interview",
        "category": "Service",
    },
    {
        "name": "Capgemini",
        "logo": "🔷",
        "hq": "Mumbai, Maharashtra",
        "available": True,
        "badge": "✅ Open",
        "badge_type": "open",
        "careers_url": "https://www.capgemini.com/in-en/careers/",
        "apply_url": "https://www.capgemini.com/in-en/careers/job-search/?search=fresher",
        "roles": [
            {"title": "Analyst – Software Engineer", "type": "Full Time"},
            {"title": "Senior Analyst", "type": "Full Time"},
            {"title": "Associate Consultant", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA / BCA / B.Sc (CS/IT)",
            "percentage": "55% and above throughout",
            "backlogs": "No active backlogs",
            "gap": "Max 1 year gap",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["C", "Java", "Python", "SQL", "English Communication", "Aptitude"],
        "package": "4 – 7.5 LPA",
        "location": "Pune, Mumbai, Bangalore, Chennai, Hyderabad, Kolkata",
        "process": "Pseudo Code Test → Behavioral Test → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "IBM India",
        "logo": "💠",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🔥 Hiring Now",
        "badge_type": "hot",
        "careers_url": "https://www.ibm.com/in-en/employment/",
        "apply_url": "https://www.ibm.com/in-en/employment/",
        "roles": [
            {"title": "Associate Software Developer", "type": "Full Time"},
            {"title": "Application Developer", "type": "Full Time"},
            {"title": "Data Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA in CSE / IT / ECE",
            "percentage": "65% and above throughout",
            "backlogs": "No backlogs",
            "gap": "No gap > 6 months",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Python", "AI/ML Basics", "Cloud (IBM Cloud)", "Java", "Data Analysis"],
        "package": "4.5 – 10 LPA",
        "location": "Bangalore, Hyderabad, Pune, Delhi NCR",
        "process": "Online Aptitude → Technical Round → Manager Round → HR",
        "category": "Product",
    },
    {
        "name": "Tech Mahindra",
        "logo": "🟤",
        "hq": "Pune, Maharashtra",
        "available": True,
        "badge": "✅ Open",
        "badge_type": "open",
        "careers_url": "https://careers.techmahindra.com/",
        "apply_url": "https://careers.techmahindra.com/ListJobs/All",
        "roles": [
            {"title": "Software Engineer Trainee", "type": "Full Time"},
            {"title": "Associate Software Engineer", "type": "Full Time"},
            {"title": "Network Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / BCA / MCA (CSE / IT / ECE preferred)",
            "percentage": "55% and above throughout",
            "backlogs": "Max 1 active backlog (cleared before joining)",
            "gap": "Max 2 years gap",
            "batch": "2023 / 2024 / 2025 passout",
        },
        "skills": ["C++", "Java", "Networking", "SQL", "OOPS Concepts"],
        "package": "3.25 – 5 LPA",
        "location": "Pune, Hyderabad, Noida, Chennai",
        "process": "Written Test → Technical Interview → HR Round",
        "category": "Service",
    },
    {
        "name": "Mindtree (LTIMindtree)",
        "logo": "🌿",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🆕 New Drive",
        "badge_type": "new",
        "careers_url": "https://www.ltimindtree.com/careers/",
        "apply_url": "https://www.ltimindtree.com/careers/",
        "roles": [
            {"title": "Graduate Engineer Trainee", "type": "Full Time"},
            {"title": "Software Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / M.Tech in CSE / IT / ECE",
            "percentage": "60% and above",
            "backlogs": "No active backlogs",
            "gap": "Max 1 year gap",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Java", "Python", "SQL", "DSA", "OOPS"],
        "package": "4 – 6.5 LPA",
        "location": "Bangalore, Hyderabad, Pune, Chennai",
        "process": "Aptitude → Coding → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "Hexaware Technologies",
        "logo": "⬡",
        "hq": "Navi Mumbai, Maharashtra",
        "available": True,
        "badge": "✅ Open",
        "badge_type": "open",
        "careers_url": "https://hexaware.com/careers/",
        "apply_url": "https://hexaware.com/careers/job-openings/",
        "roles": [
            {"title": "Software Engineer Fresher", "type": "Full Time"},
            {"title": "Associate Consultant", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / BCA / MCA (any stream)",
            "percentage": "60% and above",
            "backlogs": "No backlogs",
            "gap": "Max 1 year",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Python", "Java", "SQL", "Cloud Basics", "Agile"],
        "package": "3.5 – 6 LPA",
        "location": "Chennai, Mumbai, Pune, Bangalore",
        "process": "Online Test → Technical Round → HR",
        "category": "Service",
    },
    {
        "name": "Mphasis",
        "logo": "🔹",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🔥 Hiring Now",
        "badge_type": "hot",
        "careers_url": "https://careers.mphasis.com/",
        "apply_url": "https://careers.mphasis.com/",
        "roles": [
            {"title": "Trainee Software Engineer", "type": "Full Time"},
            {"title": "Associate Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / MCA / M.Sc(CS)",
            "percentage": "60% and above throughout",
            "backlogs": "No active backlogs",
            "gap": "Max 1 year gap",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Java", "Python", "DBMS", "Networking", "Aptitude"],
        "package": "3.5 – 5.5 LPA",
        "location": "Bangalore, Pune, Chennai",
        "process": "Aptitude Test → Technical Interview → HR",
        "category": "Service",
    },
    {
        "name": "Amazon India",
        "logo": "🟡",
        "hq": "Bangalore, Karnataka",
        "available": True,
        "badge": "🔥 High Package",
        "badge_type": "hot",
        "careers_url": "https://amazon.jobs/en/",
        "apply_url": "https://amazon.jobs/en/search?base_query=fresher+software+engineer&loc_query=India",
        "roles": [
            {"title": "SDE-1 (Software Development Engineer)", "type": "Full Time"},
            {"title": "Cloud Support Engineer", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / M.Tech in CSE / IT",
            "percentage": "Minimum 60% — strong DSA skills matter more",
            "backlogs": "No backlogs",
            "gap": "No gap preferred",
            "batch": "2024 / 2025 passout",
        },
        "skills": ["Data Structures", "Algorithms", "System Design", "Java/Python/C++", "Problem Solving"],
        "package": "18 – 35 LPA",
        "location": "Bangalore, Hyderabad, Chennai",
        "process": "Online Coding (LeetCode style) → 4–5 Technical Rounds → Bar Raiser",
        "category": "Product",
    },
    {
        "name": "Microsoft India",
        "logo": "🪟",
        "hq": "Hyderabad, Telangana",
        "available": True,
        "badge": "🔥 Dream Company",
        "badge_type": "hot",
        "careers_url": "https://careers.microsoft.com/",
        "apply_url": "https://careers.microsoft.com/us/en/search-results?keywords=fresher+india",
        "roles": [
            {"title": "Software Engineer (SWE)", "type": "Full Time"},
            {"title": "Product Manager", "type": "Full Time"},
        ],
        "eligibility": {
            "degree": "B.E / B.Tech / M.Tech in CSE / IT",
            "percentage": "CGPA 7.5+ preferred",
            "backlogs": "No backlogs",
            "gap": "No gap allowed",
            "batch": "2025 passout",
        },
        "skills": ["DSA (Advanced)", "System Design", "OOP", "C++/Java/Python", "Coding Proficiency"],
        "package": "20 – 40 LPA",
        "location": "Hyderabad, Bangalore",
        "process": "Online Coding → 4 Technical Rounds (DSA + Design + Behavioral)",
        "category": "Product",
    },
]

# ─── Naukri IT Jobs ───────────────────────────────────────────────────────────

NAUKRI_IT_JOBS = [
    {
        "title": "Software Engineer – Fresher",
        "company": "TCS",
        "location": "Chennai, Bangalore, Hyderabad",
        "experience": "0–1 Years",
        "skills": ["Python", "Java", "SQL"],
        "salary": "3.5 – 7 LPA",
        "posted": "2 days ago",
        "category": "Software Development",
        "apply_url": "https://nextstep.tcs.com/campus/",
        "naukri_url": "https://www.naukri.com/software-engineer-fresher-jobs",
        "description": "Entry-level software engineer for building scalable applications. Training provided.",
        "badge": "🔥 Hot"
    },
    {
        "title": "Python Developer – Junior",
        "company": "Infosys",
        "location": "Pune, Bangalore, Chennai",
        "experience": "0–2 Years",
        "skills": ["Python", "Django", "REST API"],
        "salary": "4 – 8 LPA",
        "posted": "1 day ago",
        "category": "Software Development",
        "apply_url": "https://career.infosys.com/joblist",
        "naukri_url": "https://www.naukri.com/python-developer-jobs-in-india",
        "description": "Looking for Python developers to work on enterprise-level projects.",
        "badge": "🆕 New"
    },
    {
        "title": "Data Analyst – Entry Level",
        "company": "Wipro",
        "location": "Hyderabad, Bangalore",
        "experience": "0–1 Years",
        "skills": ["Python", "SQL", "Excel", "Power BI"],
        "salary": "3.5 – 6 LPA",
        "posted": "3 days ago",
        "category": "Data Science / AI",
        "apply_url": "https://careers.wipro.com/",
        "naukri_url": "https://www.naukri.com/data-analyst-jobs",
        "description": "Analyze business data and create dashboards. SQL and Excel mandatory.",
        "badge": ""
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Zoho Corporation",
        "location": "Chennai, Coimbatore",
        "experience": "0–2 Years",
        "skills": ["Python", "ML", "Deep Learning", "NumPy"],
        "salary": "5 – 10 LPA",
        "posted": "Today",
        "category": "Data Science / AI",
        "apply_url": "https://careers.zohocorp.com/jobs/Careers",
        "naukri_url": "https://www.naukri.com/machine-learning-engineer-jobs",
        "description": "Build AI/ML models for Zoho's product suite. Strong Python skills required.",
        "badge": "🔥 Hot"
    },
    {
        "title": "Frontend Developer – React",
        "company": "HCL Technologies",
        "location": "Noida, Chennai, Hyderabad",
        "experience": "0–2 Years",
        "skills": ["React", "JavaScript", "HTML", "CSS"],
        "salary": "4 – 9 LPA",
        "posted": "2 days ago",
        "category": "Mobile Development",
        "apply_url": "https://www.hcltech.com/careers",
        "naukri_url": "https://www.naukri.com/react-developer-jobs",
        "description": "Develop responsive web UIs using React.js. Portfolio projects preferred.",
        "badge": ""
    },
    {
        "title": "Network Engineer – Fresher",
        "company": "Cognizant",
        "location": "Chennai, Pune, Kolkata",
        "experience": "0–1 Years",
        "skills": ["Networking", "CCNA", "Linux", "Firewall"],
        "salary": "3 – 5.5 LPA",
        "posted": "4 days ago",
        "category": "Systems / Networking",
        "apply_url": "https://careers.cognizant.com/",
        "naukri_url": "https://www.naukri.com/network-engineer-fresher-jobs",
        "description": "Configure and maintain network infrastructure. CCNA certification preferred.",
        "badge": ""
    },
    {
        "title": "Database Administrator – Junior",
        "company": "Oracle India",
        "location": "Bangalore, Hyderabad",
        "experience": "0–2 Years",
        "skills": ["SQL", "Oracle DB", "PL/SQL", "MySQL"],
        "salary": "5 – 9 LPA",
        "posted": "1 day ago",
        "category": "Database & Backend",
        "apply_url": "https://careers.oracle.com/",
        "naukri_url": "https://www.naukri.com/database-administrator-jobs",
        "description": "Manage Oracle databases, write PL/SQL procedures, and ensure data integrity.",
        "badge": "🆕 New"
    },
    {
        "title": "Android App Developer",
        "company": "Mindtree",
        "location": "Bangalore, Hyderabad",
        "experience": "0–2 Years",
        "skills": ["Java", "Android SDK", "Kotlin", "Firebase"],
        "salary": "4 – 8 LPA",
        "posted": "5 days ago",
        "category": "Mobile Development",
        "apply_url": "https://www.ltimindtree.com/careers/",
        "naukri_url": "https://www.naukri.com/android-developer-jobs",
        "description": "Develop and publish Android applications. Experience with REST APIs is a plus.",
        "badge": ""
    },
    {
        "title": "Cybersecurity Analyst – Entry Level",
        "company": "IBM India",
        "location": "Bangalore, Pune",
        "experience": "0–2 Years",
        "skills": ["Cybersecurity", "Linux", "Networking", "Python"],
        "salary": "5 – 10 LPA",
        "posted": "Today",
        "category": "Systems / Networking",
        "apply_url": "https://www.ibm.com/in-en/employment/",
        "naukri_url": "https://www.naukri.com/cyber-security-jobs",
        "description": "Monitor security threats, perform vulnerability assessments, and incident response.",
        "badge": "🔥 Hot"
    },
    {
        "title": "Full Stack Developer – MERN",
        "company": "Capgemini",
        "location": "Mumbai, Pune, Chennai",
        "experience": "0–2 Years",
        "skills": ["MongoDB", "Express", "React", "Node.js"],
        "salary": "4.5 – 9 LPA",
        "posted": "3 days ago",
        "category": "Software Development",
        "apply_url": "https://www.capgemini.com/in-en/careers/",
        "naukri_url": "https://www.naukri.com/full-stack-developer-jobs",
        "description": "Build end-to-end web applications using MERN stack. Agile environment.",
        "badge": ""
    },
    {
        "title": "AI/ML Research Engineer",
        "company": "Samsung R&D India",
        "location": "Bangalore",
        "experience": "0–1 Years",
        "skills": ["Python", "Deep Learning", "Research", "Statistics"],
        "salary": "6 – 12 LPA",
        "posted": "2 days ago",
        "category": "Data Science / AI",
        "apply_url": "https://www.naukri.com/samsung-jobs",
        "naukri_url": "https://www.naukri.com/artificial-intelligence-jobs",
        "description": "Work on cutting-edge AI research projects. Strong math and Python skills needed.",
        "badge": "🔥 Hot"
    },
    {
        "title": "Cloud Engineer – AWS/Azure",
        "company": "Accenture",
        "location": "Hyderabad, Bangalore, Chennai",
        "experience": "0–2 Years",
        "skills": ["AWS", "Azure", "Linux", "Docker"],
        "salary": "5 – 10 LPA",
        "posted": "1 day ago",
        "category": "Systems / Networking",
        "apply_url": "https://www.accenture.com/in-en/careers",
        "naukri_url": "https://www.naukri.com/cloud-engineer-jobs",
        "description": "Deploy and manage cloud infrastructure. Cloud certification is a big plus.",
        "badge": "🆕 New"
    },
]


def get_placement_data():
    """Returns all company placement data — no scraping needed."""
    open_count = sum(1 for c in PLACEMENT_COMPANIES if c.get("available"))
    return {
        "timestamp":   datetime.now().strftime("%d %b %Y, %I:%M %p"),
        "companies":   PLACEMENT_COMPANIES,
        "total_open":  open_count,
        "total":       len(PLACEMENT_COMPANIES),
        "naukri_jobs": [],
    }


def get_naukri_it_jobs():
    """Returns structured Naukri IT fresher job listings."""
    return {
        "jobs":        NAUKRI_IT_JOBS,
        "total":       len(NAUKRI_IT_JOBS),
        "source_url":  "https://www.naukri.com/it-jobs",
        "last_updated": datetime.now().strftime("%d %b %Y, %I:%M %p"),
        "categories":  sorted(list(set(j["category"] for j in NAUKRI_IT_JOBS))),
    }


# Legacy alias so app.py import still works
def fetch_placement_data(use_selenium=False):
    return get_placement_data()